### PR TITLE
TST: Re-render bot

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@beckermr, do you know why it can't push here? The error message the bot is giving doesn't seem correct as GitHub shows this line, "Add more commits by pushing to the tst_re-render branch on jakirkham-feedstocks/zlib-feedstock."

**Comment by isuruf** [comment]
Maybe github doesn't give the correct permissions for forks from organizations.

**Comment by jakirkham** [comment]
Are you able to push to this PR?

**Comment by isuruf** [comment]
Nope

**Comment by jakirkham** [comment]
Thanks for checking. Then yeah maybe there is something off with GitHub permissions here. FWIW I don't see the checkbox either.

**Comment by beckermr** [comment]
This is a known issue: https://github.com/conda-forge/conda-forge-webservices/issues/288

I think this is how github intends it. Note they mention only user accounts in their docs: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Pull request closed without merging**
