### PR TITLE
MNT: rerender

### LINKED ISSUE #55: @conda-forge-admin, please re-render
### Additional comment:

@conda-forge-admin, please re-render.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #55.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #55

### CODE REVIEW

**Comment by isuruf** [comment]
Any reason why we need this?

**Comment by jakirkham** [comment]
Was seeing some conflicts in PR ( https://github.com/conda-forge/zlib-feedstock/pull/54 ) and was thinking they might be addressed by a new re-render of `main` and the PR

**Comment by isuruf** [comment]
It's a simple conflict resolve in that PR.

**Comment by jakirkham** [comment]
Sure, don't have strong feelings about this approach or another. Just was an easy way to handle things

**Comment by ocefpaf** [comment]
In a way re-rendering does hurt, right? Merging this and you'll can also work on #54.

**Pull request merged**
