### PR TITLE
Update to 1.2.11

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` version `2.0.0`?

**Comment by xantares** [comment]
done

**Comment by xantares** [comment]
it's ready cc @jakirkham

**Comment by xantares** [comment]
ping @conda-forge/core

**Comment by xantares** [comment]
@ocefpaf the corresponding issues need to be closed, also the rerendering PRs

**Comment by ocefpaf** [comment]
Done! Thanks @xantares!!

**Pull request merged**
