### PR TITLE
Build for the linux-armv7l platform

### PR DESCRIPTION
**Pull request by jjhelmus**
Create a build of zlib for the linux-armv7l platform using the compilers and build tools from the `c4armv7l` channel.  

Regneration of feedstock was done using a modified version of conda-smithy (conda-forge/conda-smithy#1115) and conda-forge-pinning (conda-forge/conda-forge-pinning-feedstock#258) 

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjhelmus** [comment]
The `linux-armv7l` build completed but something in anaconda-client caused an error after the build.

**Comment by jjhelmus** [comment]
The `linux-armv7l` build is using `conda-forge-ci-setup` version 2.1.1 which does not have proper support for azure and therefore tried an upload with an empty token.  I can build newer versions of this package but I believe they need to be uploaded to `conda-forge` rather than `c4armv7l`.

**Comment by isuruf** [comment]
Sure. go ahead and upload a new version of conda-forge-ci-setup. You'll have to fix the whitelist of channels though. https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/conda_forge_ci_setup/build_utils.py#L84

**Comment by jjhelmus** [comment]
`c4armv7l` added to the whitelist in conda-forge/conda-forge-ci-setup-feedstock#60.  I built `conda-forge-ci-setup` on my local ARM machine and uploaded it to the `conda-forge` channel.  

This build now passes and if merged the first `armv7l` package will get uploaded via CI to `conda-forge`

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
Oops. @jjhelmus, can you rerender with your branch of conda-smithy?

**Comment by jjhelmus** [comment]
Re-rendered and armv7l build is passing

**Pull request merged**
