### PR TITLE
Disable static libraries

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #63.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by isuruf** [comment]
Static libs and headers are already in zlib which is separate to libzlib. This PR is unnecessary.

**Comment by hmaarrfk** [comment]
Therefore there is something else that is pulling in the dependencies:
```
Executing the query zlib



 Name        Version   Build              Depends                Channel     
──────────────────────────────────────────────────────────────────────────────
 libpano13   2.9.20rc2 pl5321h8a4c61d_2   zlib >=1.2.11,<1.3.0a0 conda-forge 
 cairo       1.16.0    ha61ee94_1011      zlib >=1.2.11,<1.3.0a0 conda-forge 
 freetype    2.10.4    h0708190_1         zlib >=1.2.11,<1.3.0a0 conda-forge 
 libcups     2.3.3     hf5a7f15_1         zlib >=1.2.11,<1.3.0a0 conda-forge 
 hdf4        4.2.15    h10796ff_3         zlib >=1.2.11,<1.3.0a0 conda-forge 
 pytables    3.7.0     py39h2669a42_0     zlib >=1.2.11,<1.3.0a0 conda-forge 
 libzip      1.9.2     hc869a4a_0         zlib >=1.2.12,<1.3.0a0 conda-forge 
 grpcio      1.46.3    py39h7ad10b3_2     zlib >=1.2.12,<1.3.0a0 conda-forge 
 libprotobuf 3.20.1    h6239696_0         zlib >=1.2.11,<1.3.0a0 conda-forge 
 grpc-cpp    1.46.3    hbd84cd8_2         zlib >=1.2.12,<1.3.0a0 conda-forge 
 llvmlite    0.38.1    py39h7d9a04d_0     zlib >=1.2.11,<1.3.0a0 conda-forge 
 openjpeg    2.4.0     hb52868f_1         zlib >=1.2.11,<1.3.0a0 conda-forge 
 hdf5        1.12.1    nompi_h2386368_104 zlib >=1.2.11,<1.3.0a0 conda-forge 
 libnghttp2  1.47.0    h727a467_0         zlib >=1.2.11,<1.3.0a0 conda-forge 
 libxml2     2.9.14    h22db469_3         zlib >=1.2.12,<1.3.0a0 conda-forge 
 libpng      1.6.37    h753d276_3         zlib >=1.2.12,<1.3.0a0 conda-forge 
 libssh2     1.10.0    ha56f1ee_2         zlib >=1.2.11,<1.3.0a0 conda-forge 
```

**Comment by hmaarrfk** [comment]
Is the issue this line:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml#L325

**Comment by isuruf** [comment]
No, some packages have `zlib` in run when they shouldn't

**Comment by hmaarrfk** [comment]
> No, some packages have `zlib` in run when they shouldn't

I don't really think that this is true. Lets study
https://github.com/conda-forge/libssh2-feedstock/blob/main/recipe/meta.yaml#L36

```
$ mamba repoquery depends libssh2=1.10.0=ha56f1ee_2 --no-banner

Executing the query libssh2=1.10.0=ha56f1ee_2



 Name      Version Build       Channel    
───────────────────────────────────────────
 libssh2   1.10.0  ha56f1ee_2  conda-forge
 libgcc-ng 12.1.0  h8d9b700_16 conda-forge
 openssl   1.1.1q  h166bdaf_0  conda-forge
 zlib      1.2.12  h166bdaf_2  conda-forge
```

**Comment by isuruf** [comment]
Last build of libssh2 was in September last year and `libzlib` package was introduced in October last year. So, libssh2 needs a rebuild.

**Comment by hmaarrfk** [comment]
Sorry, i didn't notice that one. 

Does it make sense to remove the the lines from conda-forge-pinnings ? Just to cleanup?

**Pull request closed without merging**
